services:
  frontend:
    build:
      context: .
      dockerfile: src/Dockerfile.frontend
      args:
        REACT_APP_API_BASE: http://localhost:5000/api  # Browser needs localhost
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: src/Dockerfile.scraper
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1